// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQY-_3tZ3MlZhGX12VIo8f-bCjzM8YtRU',
    appId: '1:607831772705:android:15b6fed601fafc1e949d60',
    messagingSenderId: '607831772705',
    projectId: 'chat-app-e4963',
    storageBucket: 'chat-app-e4963.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs_LrImFkGRofuZF-IyJGejTfhbJdGS60',
    appId: '1:607831772705:ios:1c28345fe2e57c23949d60',
    messagingSenderId: '607831772705',
    projectId: 'chat-app-e4963',
    storageBucket: 'chat-app-e4963.appspot.com',
    iosClientId:
        '607831772705-jd935p40dqt9bd2nk36k8etjha77d9jf.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
